//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类Channel。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("channel")]
    [Serializable]
    public partial class Channel
    {
        #region Model
		private int _Id;
		private string _Name;
		private bool? _Special;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[NonAutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 通道名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this._Name = value;
			}
		}
		/// <summary>
		/// 是否特殊用途，异常道口使用
		/// </summary>
		public bool? Special
		{
			get{ return _Special; }
			set
			{
				this._Special = value;
			}
		}
		#endregion
}
}
