//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类ItemCheck。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("itemcheck")]
    [Serializable]
    public partial class ItemCheck
    {
        #region Model
		private int _Id;
		private string _Item;
		private bool? _Check;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// ITEM编码
		/// </summary>
		public string Item
		{
			get{ return _Item; }
			set
			{
				this._Item = value;
			}
		}
		/// <summary>
		/// 是否需要质检
		/// </summary>
		public bool? Check
		{
			get{ return _Check; }
			set
			{
				this._Check = value;
			}
		}
		#endregion
}
}
