//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类Light。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("light")]
    [Serializable]
    public partial class Light
    {
        #region Model
		private int _Id;
		private string _Ip;
		private int? _Channel_id;
		private bool? _Inuse;
		private string _C09码;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[NonAutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 灯IP
		/// </summary>
		public string Ip
		{
			get{ return _Ip; }
			set
			{
				this._Ip = value;
			}
		}
		/// <summary>
		/// 灯所在通道号，预先配置好
		/// </summary>
		public int? Channel_id
		{
			get{ return _Channel_id; }
			set
			{
				this._Channel_id = value;
			}
		}
		/// <summary>
		/// 是否正在使用
		/// </summary>
		public bool? Inuse
		{
			get{ return _Inuse; }
			set
			{
				this._Inuse = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string C09码
		{
			get{ return _C09码; }
			set
			{
				this._C09码 = value;
			}
		}
		#endregion
}
}
