//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类LightLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("light_log")]
    [Serializable]
    public partial class LightLog
    {
        #region Model
		private int _Id;
		private int? _Light_id;
		private int? _Order_id;
		private string _Log;
		private DateTime? _Time;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 灯编号
		/// </summary>
		public int? Light_id
		{
			get{ return _Light_id; }
			set
			{
				this._Light_id = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		public int? Order_id
		{
			get{ return _Order_id; }
			set
			{
				this._Order_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Log
		{
			get{ return _Log; }
			set
			{
				this._Log = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Time
		{
			get{ return _Time; }
			set
			{
				this._Time = value;
			}
		}
		#endregion
}
}
