//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类LightHistory。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("light_history")]
    [Serializable]
    public partial class LightHistory
    {
        #region Model
		private int _Id;
		private string _Action;
		private DateTime? _Update_time;
		private string _Created_by;
		private int? _Light_id;
		private int? _Running_id;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 动作：亮灯，灭灯
		/// </summary>
		public string Action
		{
			get{ return _Action; }
			set
			{
				this._Action = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime? Update_time
		{
			get{ return _Update_time; }
			set
			{
				this._Update_time = value;
			}
		}
		/// <summary>
		/// 创建者：程序，操作人员
		/// </summary>
		public string Created_by
		{
			get{ return _Created_by; }
			set
			{
				this._Created_by = value;
			}
		}
		/// <summary>
		/// 灯编号
		/// </summary>
		public int? Light_id
		{
			get{ return _Light_id; }
			set
			{
				this._Light_id = value;
			}
		}
		/// <summary>
		/// 对应的订单编号
		/// </summary>
		public int? Running_id
		{
			get{ return _Running_id; }
			set
			{
				this._Running_id = value;
			}
		}
		#endregion
}
}
