//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类LpnC09。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("lpn09")]
    [Serializable]
    public partial class LpnC09
    {
        #region Model
		private int _Id;
		private string _Lpn;
		private string _C09码;
		private int? _State_id;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Lpn
		{
			get{ return _Lpn; }
			set
			{
				this._Lpn = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string C09码
		{
			get{ return _C09码; }
			set
			{
				this._C09码 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? State_id
		{
			get{ return _State_id; }
			set
			{
				this._State_id = value;
			}
		}
		#endregion
}
}
