//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类OrderRunning。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("order_running")]
    [Serializable]
    public partial class OrderRunning
    {
        #region Model
		private int _Id;
		private int? _Raw_id;
		private DateTime? _Update_time;
		private int? _State_id;
		private int? _Final_channel;
		private int? _Light_id;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Raw_id
		{
			get{ return _Raw_id; }
			set
			{
				this._Raw_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Update_time
		{
			get{ return _Update_time; }
			set
			{
				this._Update_time = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? State_id
		{
			get{ return _State_id; }
			set
			{
				this._State_id = value;
			}
		}
		/// <summary>
		/// 最后实际使用的通道号，可能和预分配的通道不一致
		/// </summary>
		public int? Final_channel
		{
			get{ return _Final_channel; }
			set
			{
				this._Final_channel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Light_id
		{
			get{ return _Light_id; }
			set
			{
				this._Light_id = value;
			}
		}
		#endregion
}
}
