//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类OrderRawAnalyzed。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("order_raw_analyzed")]
    [Serializable]
    public partial class OrderRawAnalyzed
    {
        #region Model
		private int _Id;
		private int? _Raw_id;
		private bool? _整托;
		private bool? _检验;
		private string _C09码;
		private int? _Channel_id;

		/// <summary>
		/// 
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		[AutoIncrementAttribute]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Raw_id
		{
			get{ return _Raw_id; }
			set
			{
				this._Raw_id = value;
			}
		}
		/// <summary>
		/// 是否整托
		/// </summary>
		public bool? 整托
		{
			get{ return _整托; }
			set
			{
				this._整托 = value;
			}
		}
		/// <summary>
		/// 是否需要检验
		/// </summary>
		public bool? 检验
		{
			get{ return _检验; }
			set
			{
				this._检验 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string C09码
		{
			get{ return _C09码; }
			set
			{
				this._C09码 = value;
			}
		}
		/// <summary>
		/// 通道号
		/// </summary>
		public int? Channel_id
		{
			get{ return _Channel_id; }
			set
			{
				this._Channel_id = value;
			}
		}
		#endregion
}
}
