//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类RawAnalyze。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("raw_analyze")]
    [Serializable]
    public partial class RawAnalyze
    {
        #region Model
		private int _Id;
		private int _整托;
		private bool? _IsCheck;
		private string _物料号;
		private string _收据号;

		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int 整托
		{
			get{ return _整托; }
			set
			{
				this._整托 = value;
			}
		}
		/// <summary>
		/// 是否需要质检
		/// </summary>
		public bool? IsCheck
		{
			get{ return _IsCheck; }
			set
			{
				this._IsCheck = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 物料号
		{
			get{ return _物料号; }
			set
			{
				this._物料号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 收据号
		{
			get{ return _收据号; }
			set
			{
				this._收据号 = value;
			}
		}
		#endregion
}
}
