//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Chloe.Annotations;
namespace LSX.PCService.Models
{
    /// <summary>
    /// 实体类ViewRawAnalyzed。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("view_raw_analyzed")]
    [Serializable]
    public partial class ViewRawAnalyzed
    {
        #region Model
		private int _Id;
		private string _箱号;
		private string _栈板号;
		private string _车牌;
		private string _发货单号;
		private string _到货地点;
		private string _物料号;
		private string _收据号;
		private string _检验标志;
		private int? _数量;
		private string _原产国;
		private string _FileId;
		private int? _检验;
		private int _整托;
		private string _C09;

		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 箱号
		{
			get{ return _箱号; }
			set
			{
				this._箱号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 栈板号
		{
			get{ return _栈板号; }
			set
			{
				this._栈板号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 车牌
		{
			get{ return _车牌; }
			set
			{
				this._车牌 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 发货单号
		{
			get{ return _发货单号; }
			set
			{
				this._发货单号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 到货地点
		{
			get{ return _到货地点; }
			set
			{
				this._到货地点 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 物料号
		{
			get{ return _物料号; }
			set
			{
				this._物料号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 收据号
		{
			get{ return _收据号; }
			set
			{
				this._收据号 = value;
			}
		}
		/// <summary>
		/// Y/N
		/// </summary>
		public string 检验标志
		{
			get{ return _检验标志; }
			set
			{
				this._检验标志 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? 数量
		{
			get{ return _数量; }
			set
			{
				this._数量 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 原产国
		{
			get{ return _原产国; }
			set
			{
				this._原产国 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FileId
		{
			get{ return _FileId; }
			set
			{
				this._FileId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? 检验
		{
			get{ return _检验; }
			set
			{
				this._检验 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int 整托
		{
			get{ return _整托; }
			set
			{
				this._整托 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string C09
		{
			get{ return _C09; }
			set
			{
				this._C09 = value;
			}
		}
		#endregion
}
}
